# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jxccommon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fjxccommon.proto\"l\n\x0fG_JXC_BaseParam\x12\x10\n\x08\x44\x61teMode\x18\x01 \x01(\x05\x12\x11\n\tStartTime\x18\x02 \x01(\t\x12\x0f\n\x07\x45ndTime\x18\x03 \x01(\t\x12\x11\n\tPageIndex\x18\x04 \x01(\x05\x12\x10\n\x08PageSize\x18\x05 \x01(\x05\x42\x19\xaa\x02\x16HandDay.Grpc.jxccommonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jxccommon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026HandDay.Grpc.jxccommon'
  _G_JXC_BASEPARAM._serialized_start=19
  _G_JXC_BASEPARAM._serialized_end=127
# @@protoc_insertion_point(module_scope)
