# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import basicInfo_pb2 as basicInfo__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in basicInfo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BasicInfoStub(object):
    """基础信息
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PageBranchDataList = channel.unary_unary(
                '/BasicInfo/PageBranchDataList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PageBranchInfoResponse.FromString,
                _registered_method=True)
        self.PageEmployeeDataList = channel.unary_unary(
                '/BasicInfo/PageEmployeeDataList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PageEmployeeInfoResponse.FromString,
                _registered_method=True)
        self.PageStockDataList = channel.unary_unary(
                '/BasicInfo/PageStockDataList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PageStockInfoResponse.FromString,
                _registered_method=True)
        self.PageSubjectDataList = channel.unary_unary(
                '/BasicInfo/PageSubjectDataList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PageSubjectInfoResponse.FromString,
                _registered_method=True)
        self.PagePriceDataList = channel.unary_unary(
                '/BasicInfo/PagePriceDataList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PagePriceInfoResponse.FromString,
                _registered_method=True)
        self.PageDepartmentList = channel.unary_unary(
                '/BasicInfo/PageDepartmentList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PageDepartmentResponse.FromString,
                _registered_method=True)
        self.ResetPush = channel.unary_unary(
                '/BasicInfo/ResetPush',
                request_serializer=basicInfo__pb2.G_ResetPushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushEmployee = channel.unary_unary(
                '/BasicInfo/PushEmployee',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushWarehouse = channel.unary_unary(
                '/BasicInfo/PushWarehouse',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushErpDiffTypeIDKey = channel.unary_unary(
                '/BasicInfo/PushErpDiffTypeIDKey',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.GetErpAutoSyncInfo = channel.unary_unary(
                '/BasicInfo/GetErpAutoSyncInfo',
                request_serializer=basicInfo__pb2.G_ErpAutoSyncInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_ErpAutoSyncInfoResponse.FromString,
                _registered_method=True)
        self.PageMenInfoDataList = channel.unary_unary(
                '/BasicInfo/PageMenInfoDataList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PageMenInfoResponse.FromString,
                _registered_method=True)
        self.GetAccountItemList = channel.unary_unary(
                '/BasicInfo/GetAccountItemList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_AccountItemReponse.FromString,
                _registered_method=True)
        self.PageTabulateInfoList = channel.unary_unary(
                '/BasicInfo/PageTabulateInfoList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=basicInfo__pb2.G_PageTabulateInfoResponse.FromString,
                _registered_method=True)
        self.PushMultiAttribute = channel.unary_unary(
                '/BasicInfo/PushMultiAttribute',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)


class BasicInfoServicer(object):
    """基础信息
    """

    def PageBranchDataList(self, request, context):
        """获取分支机构
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageEmployeeDataList(self, request, context):
        """获取职员信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageStockDataList(self, request, context):
        """获取仓库信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageSubjectDataList(self, request, context):
        """获取科目
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PagePriceDataList(self, request, context):
        """获取价格
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageDepartmentList(self, request, context):
        """获取部门
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPush(self, request, context):
        """删除监听表、重新上报数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushEmployee(self, request, context):
        """增量推送职员 G_PageEmployeeInfoResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushWarehouse(self, request, context):
        """增量推送仓库 G_PageStockInfoResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushErpDiffTypeIDKey(self, request, context):
        """增量推送客户或商品Key变更  G_PageUpdateKeyInfoResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErpAutoSyncInfo(self, request, context):
        """进销存自动同步状况信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageMenInfoDataList(self, request, context):
        """获取门店信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountItemList(self, request, context):
        """零售获取取收款账户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageTabulateInfoList(self, request, context):
        """获取制单人信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushMultiAttribute(self, request, context):
        """增量推送多属性规格资料
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PageBranchDataList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageBranchDataList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PageBranchInfoResponse.SerializeToString,
            ),
            'PageEmployeeDataList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageEmployeeDataList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PageEmployeeInfoResponse.SerializeToString,
            ),
            'PageStockDataList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageStockDataList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PageStockInfoResponse.SerializeToString,
            ),
            'PageSubjectDataList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageSubjectDataList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PageSubjectInfoResponse.SerializeToString,
            ),
            'PagePriceDataList': grpc.unary_unary_rpc_method_handler(
                    servicer.PagePriceDataList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PagePriceInfoResponse.SerializeToString,
            ),
            'PageDepartmentList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageDepartmentList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PageDepartmentResponse.SerializeToString,
            ),
            'ResetPush': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPush,
                    request_deserializer=basicInfo__pb2.G_ResetPushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.PushEmployee,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushWarehouse': grpc.unary_unary_rpc_method_handler(
                    servicer.PushWarehouse,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushErpDiffTypeIDKey': grpc.unary_unary_rpc_method_handler(
                    servicer.PushErpDiffTypeIDKey,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'GetErpAutoSyncInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErpAutoSyncInfo,
                    request_deserializer=basicInfo__pb2.G_ErpAutoSyncInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_ErpAutoSyncInfoResponse.SerializeToString,
            ),
            'PageMenInfoDataList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageMenInfoDataList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PageMenInfoResponse.SerializeToString,
            ),
            'GetAccountItemList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountItemList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_AccountItemReponse.SerializeToString,
            ),
            'PageTabulateInfoList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageTabulateInfoList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=basicInfo__pb2.G_PageTabulateInfoResponse.SerializeToString,
            ),
            'PushMultiAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMultiAttribute,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BasicInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BasicInfo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BasicInfo(object):
    """基础信息
    """

    @staticmethod
    def PageBranchDataList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PageBranchDataList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PageBranchInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageEmployeeDataList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PageEmployeeDataList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PageEmployeeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageStockDataList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PageStockDataList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PageStockInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageSubjectDataList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PageSubjectDataList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PageSubjectInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PagePriceDataList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PagePriceDataList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PagePriceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageDepartmentList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PageDepartmentList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PageDepartmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/ResetPush',
            basicInfo__pb2.G_ResetPushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PushEmployee',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushWarehouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PushWarehouse',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushErpDiffTypeIDKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PushErpDiffTypeIDKey',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErpAutoSyncInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/GetErpAutoSyncInfo',
            basicInfo__pb2.G_ErpAutoSyncInfoRequest.SerializeToString,
            basicInfo__pb2.G_ErpAutoSyncInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageMenInfoDataList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PageMenInfoDataList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PageMenInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountItemList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/GetAccountItemList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_AccountItemReponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageTabulateInfoList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PageTabulateInfoList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            basicInfo__pb2.G_PageTabulateInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushMultiAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasicInfo/PushMultiAttribute',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
