# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: initialization.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'initialization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14initialization.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"P\n\x12G_WhiteListRequest\x12\x0e\n\x06\x43orpId\x18\x01 \x01(\x01\x12\x0e\n\x06\x45rpBId\x18\x02 \x01(\x01\x12\x0b\n\x03Key\x18\x03 \x01(\t\x12\r\n\x05Value\x18\x04 \x01(\x05\"P\n\x1bG_WhiteListCollectonRequest\x12!\n\x04List\x18\x01 \x03(\x0b\x32\x13.G_WhiteListRequest\x12\x0e\n\x06\x43orpId\x18\x02 \x01(\x03\"<\n\x1cG_CheckErpConnectionResponse\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\x0b\n\x03Msg\x18\x02 \x01(\t\"U\n\x15G_DataBaseListRequest\x12\x14\n\x0cJxcDBAddress\x18\x01 \x01(\t\x12\x14\n\x0cJxcDBAccount\x18\x02 \x01(\t\x12\x10\n\x08JxcDBPwd\x18\x03 \x01(\t\"*\n\x16G_DataBaseListResponse\x12\x10\n\x08\x44\x61taBase\x18\x01 \x03(\t2\xf7\x04\n\x0eInitialization\x12L\n\rInitSqlScript\x12\x1c.G_WhiteListCollectonRequest\x1a\x1d.G_CheckErpConnectionResponse\x12K\n\x12\x43heckErpConnection\x12\x16.google.protobuf.Empty\x1a\x1d.G_CheckErpConnectionResponse\x12\x42\n\x0fGetDataBaseList\x12\x16.google.protobuf.Empty\x1a\x17.G_DataBaseListResponse\x12L\n\x14GetCustomerWhiteList\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValue\x12R\n\x14SetCustomerWhiteList\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\x12U\n\x17RemoveCustomerWhiteList\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\x12\x46\n\x0eTestGRPCPorwer\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValue\x12\x45\n\rGetGrpcVerion\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValueB\x1e\xaa\x02\x1bHandDay.Grpc.Initializationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'initialization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033HandDay.Grpc.Initialization'
  _globals['_G_WHITELISTREQUEST']._serialized_start=85
  _globals['_G_WHITELISTREQUEST']._serialized_end=165
  _globals['_G_WHITELISTCOLLECTONREQUEST']._serialized_start=167
  _globals['_G_WHITELISTCOLLECTONREQUEST']._serialized_end=247
  _globals['_G_CHECKERPCONNECTIONRESPONSE']._serialized_start=249
  _globals['_G_CHECKERPCONNECTIONRESPONSE']._serialized_end=309
  _globals['_G_DATABASELISTREQUEST']._serialized_start=311
  _globals['_G_DATABASELISTREQUEST']._serialized_end=396
  _globals['_G_DATABASELISTRESPONSE']._serialized_start=398
  _globals['_G_DATABASELISTRESPONSE']._serialized_end=440
  _globals['_INITIALIZATION']._serialized_start=443
  _globals['_INITIALIZATION']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
