# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import member_pb2 as member__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in member_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemberStub(object):
    """会员管理
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PageMemberClassifyList = channel.unary_unary(
                '/Member/PageMemberClassifyList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=member__pb2.G_MemberClassifyListResponse.FromString,
                _registered_method=True)
        self.MemberPullTask = channel.unary_unary(
                '/Member/MemberPullTask',
                request_serializer=member__pb2.G_MemberPullTaskRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.MemberSynchroList = channel.unary_unary(
                '/Member/MemberSynchroList',
                request_serializer=member__pb2.G_MemberListSynchroRequest.SerializeToString,
                response_deserializer=member__pb2.G_MemberListSynchroResponse.FromString,
                _registered_method=True)
        self.PageMemberTradeStatisticsList = channel.unary_unary(
                '/Member/PageMemberTradeStatisticsList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=member__pb2.G_PageMemberTradeStatisticsResponse.FromString,
                _registered_method=True)
        self.PageMemberStoredList = channel.unary_unary(
                '/Member/PageMemberStoredList',
                request_serializer=member__pb2.G_PageMemberRecordRequest.SerializeToString,
                response_deserializer=member__pb2.G_PageMemberRecordResponse.FromString,
                _registered_method=True)
        self.PageMemberIntegralList = channel.unary_unary(
                '/Member/PageMemberIntegralList',
                request_serializer=member__pb2.G_PageMemberRecordRequest.SerializeToString,
                response_deserializer=member__pb2.G_PageMemberRecordResponse.FromString,
                _registered_method=True)
        self.PageMemberTradeList = channel.unary_unary(
                '/Member/PageMemberTradeList',
                request_serializer=member__pb2.G_PageMemberRecordRequest.SerializeToString,
                response_deserializer=member__pb2.G_PageMemberRecordResponse.FromString,
                _registered_method=True)
        self.PageMemberIntegralBalanceList = channel.unary_unary(
                '/Member/PageMemberIntegralBalanceList',
                request_serializer=common__pb2.G_BaseInfoRequest.SerializeToString,
                response_deserializer=member__pb2.G_PageMemberIntegralBalanceListResponse.FromString,
                _registered_method=True)
        self.SynchroMemberIntegralList = channel.unary_unary(
                '/Member/SynchroMemberIntegralList',
                request_serializer=member__pb2.G_SynchroMemberIntegralListRequest.SerializeToString,
                response_deserializer=member__pb2.G_SynchroMemberIntegralListResponse.FromString,
                _registered_method=True)
        self.UpdateMemberMatchingState = channel.unary_unary(
                '/Member/UpdateMemberMatchingState',
                request_serializer=member__pb2.G_UpdateMemberMatchingStateRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.UpdateMemberInfo = channel.unary_unary(
                '/Member/UpdateMemberInfo',
                request_serializer=member__pb2.G_MemberBaseInfoUpdateRequest.SerializeToString,
                response_deserializer=member__pb2.G_MemberBaseInfoUpdateListResponse.FromString,
                _registered_method=True)
        self.UpdateRetailCouponState = channel.unary_unary(
                '/Member/UpdateRetailCouponState',
                request_serializer=member__pb2.G_RetailCouponStateUpdateRequest.SerializeToString,
                response_deserializer=member__pb2.G_RetailCouponStateUpdateListResponse.FromString,
                _registered_method=True)
        self.SynchroCouponList = channel.unary_unary(
                '/Member/SynchroCouponList',
                request_serializer=member__pb2.G_SynchroCouponListRequest.SerializeToString,
                response_deserializer=member__pb2.G_SynchroCouponListResponse.FromString,
                _registered_method=True)
        self.PushChangeMember = channel.unary_unary(
                '/Member/PushChangeMember',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushCouponUseState = channel.unary_unary(
                '/Member/PushCouponUseState',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushMemberTradeReport = channel.unary_unary(
                '/Member/PushMemberTradeReport',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)


class MemberServicer(object):
    """会员管理
    """

    def PageMemberClassifyList(self, request, context):
        """获取会员分类
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemberPullTask(self, request, context):
        """拉取ERP会员 G_MemberPullTaskResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemberSynchroList(self, request, context):
        """会员同步到ERP
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageMemberTradeStatisticsList(self, request, context):
        """会员交易统计
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageMemberStoredList(self, request, context):
        """会员储值信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageMemberIntegralList(self, request, context):
        """会员积分记录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageMemberTradeList(self, request, context):
        """会员交易信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PageMemberIntegralBalanceList(self, request, context):
        """会员积分余额
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynchroMemberIntegralList(self, request, context):
        """同步会员积分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemberMatchingState(self, request, context):
        """更新会员的匹配状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemberInfo(self, request, context):
        """更新会员基础信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRetailCouponState(self, request, context):
        """更新零售对应ERP优惠券状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynchroCouponList(self, request, context):
        """同步优惠券
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushChangeMember(self, request, context):
        """推送积分余额发生变化的会员 G_PageMemberIntegralBalanceListResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushCouponUseState(self, request, context):
        """增量推送优惠卷使用状态 G_PageCouponUseStateResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushMemberTradeReport(self, request, context):
        """增量推送会员交易数据 G_PageMemberTradeStatisticsResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PageMemberClassifyList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageMemberClassifyList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=member__pb2.G_MemberClassifyListResponse.SerializeToString,
            ),
            'MemberPullTask': grpc.unary_unary_rpc_method_handler(
                    servicer.MemberPullTask,
                    request_deserializer=member__pb2.G_MemberPullTaskRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'MemberSynchroList': grpc.unary_unary_rpc_method_handler(
                    servicer.MemberSynchroList,
                    request_deserializer=member__pb2.G_MemberListSynchroRequest.FromString,
                    response_serializer=member__pb2.G_MemberListSynchroResponse.SerializeToString,
            ),
            'PageMemberTradeStatisticsList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageMemberTradeStatisticsList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=member__pb2.G_PageMemberTradeStatisticsResponse.SerializeToString,
            ),
            'PageMemberStoredList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageMemberStoredList,
                    request_deserializer=member__pb2.G_PageMemberRecordRequest.FromString,
                    response_serializer=member__pb2.G_PageMemberRecordResponse.SerializeToString,
            ),
            'PageMemberIntegralList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageMemberIntegralList,
                    request_deserializer=member__pb2.G_PageMemberRecordRequest.FromString,
                    response_serializer=member__pb2.G_PageMemberRecordResponse.SerializeToString,
            ),
            'PageMemberTradeList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageMemberTradeList,
                    request_deserializer=member__pb2.G_PageMemberRecordRequest.FromString,
                    response_serializer=member__pb2.G_PageMemberRecordResponse.SerializeToString,
            ),
            'PageMemberIntegralBalanceList': grpc.unary_unary_rpc_method_handler(
                    servicer.PageMemberIntegralBalanceList,
                    request_deserializer=common__pb2.G_BaseInfoRequest.FromString,
                    response_serializer=member__pb2.G_PageMemberIntegralBalanceListResponse.SerializeToString,
            ),
            'SynchroMemberIntegralList': grpc.unary_unary_rpc_method_handler(
                    servicer.SynchroMemberIntegralList,
                    request_deserializer=member__pb2.G_SynchroMemberIntegralListRequest.FromString,
                    response_serializer=member__pb2.G_SynchroMemberIntegralListResponse.SerializeToString,
            ),
            'UpdateMemberMatchingState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemberMatchingState,
                    request_deserializer=member__pb2.G_UpdateMemberMatchingStateRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'UpdateMemberInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemberInfo,
                    request_deserializer=member__pb2.G_MemberBaseInfoUpdateRequest.FromString,
                    response_serializer=member__pb2.G_MemberBaseInfoUpdateListResponse.SerializeToString,
            ),
            'UpdateRetailCouponState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRetailCouponState,
                    request_deserializer=member__pb2.G_RetailCouponStateUpdateRequest.FromString,
                    response_serializer=member__pb2.G_RetailCouponStateUpdateListResponse.SerializeToString,
            ),
            'SynchroCouponList': grpc.unary_unary_rpc_method_handler(
                    servicer.SynchroCouponList,
                    request_deserializer=member__pb2.G_SynchroCouponListRequest.FromString,
                    response_serializer=member__pb2.G_SynchroCouponListResponse.SerializeToString,
            ),
            'PushChangeMember': grpc.unary_unary_rpc_method_handler(
                    servicer.PushChangeMember,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushCouponUseState': grpc.unary_unary_rpc_method_handler(
                    servicer.PushCouponUseState,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushMemberTradeReport': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMemberTradeReport,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Member', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Member', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Member(object):
    """会员管理
    """

    @staticmethod
    def PageMemberClassifyList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PageMemberClassifyList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            member__pb2.G_MemberClassifyListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemberPullTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/MemberPullTask',
            member__pb2.G_MemberPullTaskRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemberSynchroList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/MemberSynchroList',
            member__pb2.G_MemberListSynchroRequest.SerializeToString,
            member__pb2.G_MemberListSynchroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageMemberTradeStatisticsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PageMemberTradeStatisticsList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            member__pb2.G_PageMemberTradeStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageMemberStoredList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PageMemberStoredList',
            member__pb2.G_PageMemberRecordRequest.SerializeToString,
            member__pb2.G_PageMemberRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageMemberIntegralList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PageMemberIntegralList',
            member__pb2.G_PageMemberRecordRequest.SerializeToString,
            member__pb2.G_PageMemberRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageMemberTradeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PageMemberTradeList',
            member__pb2.G_PageMemberRecordRequest.SerializeToString,
            member__pb2.G_PageMemberRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PageMemberIntegralBalanceList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PageMemberIntegralBalanceList',
            common__pb2.G_BaseInfoRequest.SerializeToString,
            member__pb2.G_PageMemberIntegralBalanceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynchroMemberIntegralList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/SynchroMemberIntegralList',
            member__pb2.G_SynchroMemberIntegralListRequest.SerializeToString,
            member__pb2.G_SynchroMemberIntegralListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMemberMatchingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/UpdateMemberMatchingState',
            member__pb2.G_UpdateMemberMatchingStateRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMemberInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/UpdateMemberInfo',
            member__pb2.G_MemberBaseInfoUpdateRequest.SerializeToString,
            member__pb2.G_MemberBaseInfoUpdateListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRetailCouponState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/UpdateRetailCouponState',
            member__pb2.G_RetailCouponStateUpdateRequest.SerializeToString,
            member__pb2.G_RetailCouponStateUpdateListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynchroCouponList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/SynchroCouponList',
            member__pb2.G_SynchroCouponListRequest.SerializeToString,
            member__pb2.G_SynchroCouponListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushChangeMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PushChangeMember',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushCouponUseState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PushCouponUseState',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushMemberTradeReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Member/PushMemberTradeReport',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
