# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: operation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foperation.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x7f\n\x08\x46ilePart\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12.\n\tfile_data\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.BytesValue\x12\x30\n\nname_space\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"E\n\x0c\x46ileOpResult\x12\n\n\x02ok\x18\x01 \x01(\x08\x12)\n\x03msg\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue2\xf8\x02\n\tOperation\x12\x45\n\rGetGrpcVerion\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValue\x12&\n\x08SendFile\x12\t.FilePart\x1a\r.FileOpResult(\x01\x12N\n\x10RestGrpcServices\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\x12T\n\x16GetGrpcServicesDllInfo\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\x12V\n\x18GetGrpcWindowServiceName\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValueB\x19\xaa\x02\x16HandDay.Grpc.Operationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\026HandDay.Grpc.Operation'
  _globals['_FILEPART']._serialized_start=80
  _globals['_FILEPART']._serialized_end=207
  _globals['_FILEOPRESULT']._serialized_start=209
  _globals['_FILEOPRESULT']._serialized_end=278
  _globals['_OPERATION']._serialized_start=281
  _globals['_OPERATION']._serialized_end=657
# @@protoc_insertion_point(module_scope)
