# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderStub(object):
    """订单管理
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynchroSaleOrderList = channel.unary_unary(
                '/Order/SynchroSaleOrderList',
                request_serializer=order__pb2.G_SyncBillListRequest.SerializeToString,
                response_deserializer=order__pb2.G_SyncBillListInfoResponse.FromString,
                _registered_method=True)
        self.SynchroReceiptOrderList = channel.unary_unary(
                '/Order/SynchroReceiptOrderList',
                request_serializer=order__pb2.G_SyncBillListRequest.SerializeToString,
                response_deserializer=order__pb2.G_SyncBillListInfoResponse.FromString,
                _registered_method=True)
        self.SynchroLsSaleOrderList = channel.unary_unary(
                '/Order/SynchroLsSaleOrderList',
                request_serializer=order__pb2.G_SyncBillListRequest.SerializeToString,
                response_deserializer=order__pb2.G_SyncBillListInfoResponse.FromString,
                _registered_method=True)
        self.PushPostBill = channel.unary_unary(
                '/Order/PushPostBill',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushDeleteBill = channel.unary_unary(
                '/Order/PushDeleteBill',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushDeliveryBill = channel.unary_unary(
                '/Order/PushDeliveryBill',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushBillCenterList = channel.unary_unary(
                '/Order/PushBillCenterList',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=common__pb2.G_PushResponse.FromString,
                _registered_method=True)
        self.PushOutBillSync = channel.unary_unary(
                '/Order/PushOutBillSync',
                request_serializer=common__pb2.G_PushRequest.SerializeToString,
                response_deserializer=order__pb2.G_ErpOutBillResponse.FromString,
                _registered_method=True)


class OrderServicer(object):
    """订单管理
    """

    def SynchroSaleOrderList(self, request, context):
        """同步销售订单（订单，销售单，退货单，合在一起）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynchroReceiptOrderList(self, request, context):
        """同步收款单、付款单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynchroLsSaleOrderList(self, request, context):
        """同步零售单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushPostBill(self, request, context):
        """增量推送已过账的单据（1 销售出库  2 销售退货 3 收款 4 付款） G_PagePushBillResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushDeleteBill(self, request, context):
        """增量推送ERP已删除的单据（ 1 销售出库  2 销售退货 3 收款 4 付款） G_PagePushBillResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushDeliveryBill(self, request, context):
        """推送已出库订单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushBillCenterList(self, request, context):
        """增量推送 管家婆云 单据信息 （出库、退换货单 用于 CRM查询8大交易数据）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushOutBillSync(self, request, context):
        """手动拉去erp中单据到指掌订货系统中
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynchroSaleOrderList': grpc.unary_unary_rpc_method_handler(
                    servicer.SynchroSaleOrderList,
                    request_deserializer=order__pb2.G_SyncBillListRequest.FromString,
                    response_serializer=order__pb2.G_SyncBillListInfoResponse.SerializeToString,
            ),
            'SynchroReceiptOrderList': grpc.unary_unary_rpc_method_handler(
                    servicer.SynchroReceiptOrderList,
                    request_deserializer=order__pb2.G_SyncBillListRequest.FromString,
                    response_serializer=order__pb2.G_SyncBillListInfoResponse.SerializeToString,
            ),
            'SynchroLsSaleOrderList': grpc.unary_unary_rpc_method_handler(
                    servicer.SynchroLsSaleOrderList,
                    request_deserializer=order__pb2.G_SyncBillListRequest.FromString,
                    response_serializer=order__pb2.G_SyncBillListInfoResponse.SerializeToString,
            ),
            'PushPostBill': grpc.unary_unary_rpc_method_handler(
                    servicer.PushPostBill,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushDeleteBill': grpc.unary_unary_rpc_method_handler(
                    servicer.PushDeleteBill,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushDeliveryBill': grpc.unary_unary_rpc_method_handler(
                    servicer.PushDeliveryBill,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushBillCenterList': grpc.unary_unary_rpc_method_handler(
                    servicer.PushBillCenterList,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=common__pb2.G_PushResponse.SerializeToString,
            ),
            'PushOutBillSync': grpc.unary_unary_rpc_method_handler(
                    servicer.PushOutBillSync,
                    request_deserializer=common__pb2.G_PushRequest.FromString,
                    response_serializer=order__pb2.G_ErpOutBillResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Order', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Order', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Order(object):
    """订单管理
    """

    @staticmethod
    def SynchroSaleOrderList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/SynchroSaleOrderList',
            order__pb2.G_SyncBillListRequest.SerializeToString,
            order__pb2.G_SyncBillListInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynchroReceiptOrderList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/SynchroReceiptOrderList',
            order__pb2.G_SyncBillListRequest.SerializeToString,
            order__pb2.G_SyncBillListInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynchroLsSaleOrderList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/SynchroLsSaleOrderList',
            order__pb2.G_SyncBillListRequest.SerializeToString,
            order__pb2.G_SyncBillListInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushPostBill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/PushPostBill',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushDeleteBill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/PushDeleteBill',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushDeliveryBill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/PushDeliveryBill',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushBillCenterList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/PushBillCenterList',
            common__pb2.G_PushRequest.SerializeToString,
            common__pb2.G_PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushOutBillSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Order/PushOutBillSync',
            common__pb2.G_PushRequest.SerializeToString,
            order__pb2.G_ErpOutBillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
